CREATE SEQUENCE Adresy_ID_Sek START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE Osoby_ID_Sek START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE Klienci_ID_Sek START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE Stanowiska_ID_Sek START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE Pracownicy_ID_Sek START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE Stanowiska_pracownikow_ID_Sek START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE Kategorie_produktow_ID_Sek START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE Producenci_ID_Sek START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE Lokalizacje_produktow_ID_Sek START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE Produkty_ID_Sek START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE Zamowienia_ID_Sek START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE Zamowienia_produkty_ID_Sek START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE Uslugi_ID_Sek START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE Zlecenia_uslug_ID_Sek START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE Pracownicy_zlecen_ID_Sek START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

INSERT INTO Adresy VALUES(Adresy_ID_Sek.nextval, 'Kielce', 'Swietokrzyska', '92', '14');
INSERT INTO Adresy VALUES(Adresy_ID_Sek.nextval, 'Checiny', 'Szkolna', '91', '24');
INSERT INTO Adresy VALUES(Adresy_ID_Sek.nextval, 'Staporkow', 'Chopina', '80', '10');
INSERT INTO Adresy VALUES(Adresy_ID_Sek.nextval, 'Morawica', 'Niebieska', '62', '42');
INSERT INTO Adresy VALUES(Adresy_ID_Sek.nextval, 'Cedzyna', 'Kielecka', '64', '28');
INSERT INTO Adresy VALUES(Adresy_ID_Sek.nextval, 'Ciekoty', 'Parcela', '113', '25');
INSERT INTO Adresy VALUES(Adresy_ID_Sek.nextval, 'Kostomloty', 'Maciejowka', '81', '12');
INSERT INTO Adresy VALUES(Adresy_ID_Sek.nextval, 'Piekoszow', 'Wolnosci', '48', '44');
INSERT INTO Adresy VALUES(Adresy_ID_Sek.nextval, 'Daleszyce', 'Sienkiewicza', '41', '56');
INSERT INTO Adresy VALUES(Adresy_ID_Sek.nextval, 'Krajno', 'Pogorzele', '122', '49');
INSERT INTO Adresy VALUES(Adresy_ID_Sek.nextval, 'Mniow', 'Gajowa', '23', '45');
INSERT INTO Adresy VALUES(Adresy_ID_Sek.nextval, 'Gliniany Las', 'Koscielna', '19', '27');
INSERT INTO Adresy VALUES(Adresy_ID_Sek.nextval, 'Chancza', 'Zalewska', '33', '56');
INSERT INTO Adresy VALUES(Adresy_ID_Sek.nextval, 'Makoszyn', 'Wiejska', '132', '55');
INSERT INTO Adresy VALUES(Adresy_ID_Sek.nextval, 'Gorno', 'Dolna', '96', '33');
INSERT INTO Adresy VALUES(Adresy_ID_Sek.nextval, 'Krakow', 'Krakowska', '36', '49');
INSERT INTO Adresy VALUES(Adresy_ID_Sek.nextval, 'Warszawa', 'Warszawska', '103', '17');
INSERT INTO Adresy VALUES(Adresy_ID_Sek.nextval, 'Wroclaw', 'Wroclawska', '26', '33');
INSERT INTO Adresy VALUES(Adresy_ID_Sek.nextval, 'Poznan', 'Poznanska', '38', '59');
INSERT INTO Adresy VALUES(Adresy_ID_Sek.nextval, 'Lublin', 'Lublinska', '2', '30');
INSERT INTO Adresy VALUES(Adresy_ID_Sek.nextval, 'Zamosc', 'Zamozna', '34', '32');
INSERT INTO Adresy VALUES(Adresy_ID_Sek.nextval, 'Gdynia', 'Gdynska', '125', '57');
INSERT INTO Adresy VALUES(Adresy_ID_Sek.nextval, 'Gdansk', 'Gdanska', '140', '36');
INSERT INTO Adresy VALUES(Adresy_ID_Sek.nextval, 'Sopot', 'Sopocka', '146', '8');
INSERT INTO Adresy VALUES(Adresy_ID_Sek.nextval, 'Czestochowa', 'Czestochowska', '2', '19');
INSERT INTO Adresy VALUES(Adresy_ID_Sek.nextval, 'Bialystok', 'Bialostocka', '145', '44');
INSERT INTO Adresy VALUES(Adresy_ID_Sek.nextval, 'Lodz', 'Lodzka', '39', '39');
INSERT INTO Adresy VALUES(Adresy_ID_Sek.nextval, 'Bydgoszcz', 'Smieciowa', '142', '1');
INSERT INTO Adresy VALUES(Adresy_ID_Sek.nextval, 'Szczecin', 'Szczecinska', '46', '32');
INSERT INTO Adresy VALUES(Adresy_ID_Sek.nextval, 'Katowice', 'Katowicka', '126', '2');

INSERT INTO Osoby VALUES(Osoby_ID_Sek.nextval, 1, 'Kristina', 'Valevska', sysdate - 30148, '11111137835', '111129952', 'k.valevska@gmail.com', 'K');
INSERT INTO Osoby VALUES(Osoby_ID_Sek.nextval, 2, 'Ewa', 'Braun', sysdate - 28759, '11111116366', '111112691', 'e.braun@gmail.com', 'K');
INSERT INTO Osoby VALUES(Osoby_ID_Sek.nextval, 3, 'Anna', 'Zalewska', sysdate - 31226, '11111140450', '111115146', 'a.zalewska@gmail.com', 'K');
INSERT INTO Osoby VALUES(Osoby_ID_Sek.nextval, 4, 'Teresa', 'Ostrowska', sysdate - 29515, '11111143804', '111114023', 't.ostrowska@gmail.com', 'K');
INSERT INTO Osoby VALUES(Osoby_ID_Sek.nextval, 5, 'Halina', 'Kwiatkowska', sysdate - 11652, '11111129655', '111115033', 'h.kwiatkowska@gmail.com', 'K');
INSERT INTO Osoby VALUES(Osoby_ID_Sek.nextval, 6, 'Igor', 'Kowalski', sysdate - 31321, '11111127174', '111119699', 'i.kowalski@gmail.com', 'M');
INSERT INTO Osoby VALUES(Osoby_ID_Sek.nextval, 7, 'Jacek', 'Nowak', sysdate - 33156, '11111133572', '111132329', 'j.nowak@gmail.com', 'M');
INSERT INTO Osoby VALUES(Osoby_ID_Sek.nextval, 8, 'Szymon', 'Kolodziejczyk', sysdate - 8481, '11111120422', '111133548', 's.kolodziejczyk@gmail.com', 'M');
INSERT INTO Osoby VALUES(Osoby_ID_Sek.nextval, 9, 'Michal ', 'Kwaczor', sysdate - 19374, '11111131524', '111116171', 'm.kwaczor@gmail.com', 'M');
INSERT INTO Osoby VALUES(Osoby_ID_Sek.nextval, 10, 'Pawel', 'Piotrowski', sysdate - 24246, '11111142417', '111142792', 'p.piotrowski@gmail.com', 'M');
INSERT INTO Osoby VALUES(Osoby_ID_Sek.nextval, 11, 'Jakub', 'Kotwica', sysdate - 30752, '11111135943', '111142232', 'j.kotwica@gmail.com', 'M');
INSERT INTO Osoby VALUES(Osoby_ID_Sek.nextval, 12, 'Bartlomiej', 'Bugara', sysdate - 18533, '11111124510', '111114989', 'b.bugara@gmail.com', 'M');
INSERT INTO Osoby VALUES(Osoby_ID_Sek.nextval, 13, 'Janusz', 'Gajos', sysdate - 33964, '11111128777', '111116994', 'j.gajos@gmail.com', 'M');
INSERT INTO Osoby VALUES(Osoby_ID_Sek.nextval, 14, 'Tomasz', 'Rak', sysdate - 24767, '11111124141', '111139918', 't.rak@gmail.com', 'M');
INSERT INTO Osoby VALUES(Osoby_ID_Sek.nextval, 15, 'Maciej', 'Kozlowski', sysdate - 11713, '11111124676', '111114370', 'm.kozlowski@gmail.com', 'M');
INSERT INTO Osoby VALUES(Osoby_ID_Sek.nextval, 16, 'Ireneusz', 'Krupa', sysdate - 13150, '11111119357', '111126311', 'i.krupa@gmail.com', 'M');
INSERT INTO Osoby VALUES(Osoby_ID_Sek.nextval, 17, 'Gracjan', 'Glowacki', sysdate - 6894, '11111121182', '111127225', 'g.glowacki@gmail.com', 'M');
INSERT INTO Osoby VALUES(Osoby_ID_Sek.nextval, 18, 'Marcin', 'Jankowski', sysdate - 24866, '11111133976', '111116547', 'm.jankowski@gmail.com', 'M');
INSERT INTO Osoby VALUES(Osoby_ID_Sek.nextval, 19, 'Mateusz', 'Chmielewski', sysdate - 35767, '11111126232', '111131091', 'm.chmielewski@gmail.com', 'M');
INSERT INTO Osoby VALUES(Osoby_ID_Sek.nextval, 20, 'Kordian', 'Sikora', sysdate - 32609, '11111118490', '111139100', 'k.sikora@gmail.com', 'M');
INSERT INTO Osoby VALUES(Osoby_ID_Sek.nextval, 21, 'Ignacy', 'Witkowski', sysdate - 9067, '11111142946', '111125418', 'i.witkowski@gmail.com', 'M');
INSERT INTO Osoby VALUES(Osoby_ID_Sek.nextval, 22, 'Cyprian', 'Cieslak', sysdate - 25634, '11111112551', '111140843', 'c.cieslak@gmail.com', 'M');
INSERT INTO Osoby VALUES(Osoby_ID_Sek.nextval, 23, 'Ariel', 'Kalinowski', sysdate - 14394, '11111142743', '111132928', 'a.kalinowski@gmail.com', 'M');
INSERT INTO Osoby VALUES(Osoby_ID_Sek.nextval, 24, 'Kornel', 'Malinowski', sysdate - 16288, '11111130446', '111127662', 'k.malinowski@gmail.com', 'M');
INSERT INTO Osoby VALUES(Osoby_ID_Sek.nextval, 25, 'Janusz', 'Brzezinski', sysdate - 33256, '11111140621', '111129721', 'j.brzezinski@gmail.com', 'M');
INSERT INTO Osoby VALUES(Osoby_ID_Sek.nextval, 26, 'Irena', 'Szymczak', sysdate - 19128, '11111117649', '111121630', 'i.szymczak@gmail.com', 'K');
INSERT INTO Osoby VALUES(Osoby_ID_Sek.nextval, 27, 'Izyda', 'Jankowska', sysdate - 28679, '11111133116', '111123242', 'i.jankowska@gmail.com', 'K');
INSERT INTO Osoby VALUES(Osoby_ID_Sek.nextval, 28, 'Maja', 'Wlodarczyk', sysdate - 10451, '11111114591', '111132416', 'm.wlodarczyk@gmail.com', 'K');
INSERT INTO Osoby VALUES(Osoby_ID_Sek.nextval, 29, 'Alina', 'Mazur', sysdate - 19110, '11111141684', '111111587', 'a.mazur@gmail.com', 'K');
INSERT INTO Osoby VALUES(Osoby_ID_Sek.nextval, 30, 'Eliza', 'Maciejewska', sysdate - 11303, '11111124741', '111136130', 'e.maciejewska@gmail.com', 'K');

INSERT INTO Klienci VALUES(Klienci_ID_Sek.nextval, 1, sysdate - 418, '', '');
INSERT INTO Klienci VALUES(Klienci_ID_Sek.nextval, 2, sysdate - 1078, '', '');
INSERT INTO Klienci VALUES(Klienci_ID_Sek.nextval, 3, sysdate - 1852, '', '');
INSERT INTO Klienci VALUES(Klienci_ID_Sek.nextval, 4, sysdate - 455, '', '0123456789');
INSERT INTO Klienci VALUES(Klienci_ID_Sek.nextval, 5, sysdate - 1026, '', '');
INSERT INTO Klienci VALUES(Klienci_ID_Sek.nextval, 6, sysdate - 622, '', '');
INSERT INTO Klienci VALUES(Klienci_ID_Sek.nextval, 7, sysdate - 802, '', '');
INSERT INTO Klienci VALUES(Klienci_ID_Sek.nextval, 8, sysdate - 1372, '', '');
INSERT INTO Klienci VALUES(Klienci_ID_Sek.nextval, 9, sysdate - 1279, '', '9876543210');
INSERT INTO Klienci VALUES(Klienci_ID_Sek.nextval, 10, sysdate - 1027, '', '');
INSERT INTO Klienci VALUES(Klienci_ID_Sek.nextval, 11, sysdate - 819, '', '');
INSERT INTO Klienci VALUES(Klienci_ID_Sek.nextval, 12, sysdate - 1325, '', '');
INSERT INTO Klienci VALUES(Klienci_ID_Sek.nextval, 13, sysdate - 1409, '', '');
INSERT INTO Klienci VALUES(Klienci_ID_Sek.nextval, 14, sysdate - 666, '', '');
INSERT INTO Klienci VALUES(Klienci_ID_Sek.nextval, 15, sysdate - 1181, '', '');

INSERT INTO Stanowiska VALUES(Stanowiska_ID_Sek.nextval, 'prezes', 'zarzadzanie firma');
INSERT INTO Stanowiska VALUES(Stanowiska_ID_Sek.nextval, 'kierownik', 'zarzadzanie praca pracownikow, kontrola czasu pracy');
INSERT INTO Stanowiska VALUES(Stanowiska_ID_Sek.nextval, 'sprzedawca', 'obsluga klientow');
INSERT INTO Stanowiska VALUES(Stanowiska_ID_Sek.nextval, 'monter', 'montaz mebli');
INSERT INTO Stanowiska VALUES(Stanowiska_ID_Sek.nextval, 'magazynier', 'monitorowanie stanow magazynowych');
INSERT INTO Stanowiska VALUES(Stanowiska_ID_Sek.nextval, 'doradca klienta', 'pomoc klientom w wyborze mebli');
INSERT INTO Stanowiska VALUES(Stanowiska_ID_Sek.nextval, 'logistyk', 'przygotowywanie przesylek');
INSERT INTO Stanowiska VALUES(Stanowiska_ID_Sek.nextval, 'technik', 'serwisowanie sprzetu oraz jego konserwacja');
INSERT INTO Stanowiska VALUES(Stanowiska_ID_Sek.nextval, 'konsultant sprzedazy', 'negocjacje z klientami, znajomosc oferty');
INSERT INTO Stanowiska VALUES(Stanowiska_ID_Sek.nextval, 'asystent', 'wspiera prace prezesa oraz kierownikow');
INSERT INTO Stanowiska VALUES(Stanowiska_ID_Sek.nextval, 'pracownik zewnetrzny', 'wykonuje zlecone mu zadania z danego zakresu');
INSERT INTO Stanowiska VALUES(Stanowiska_ID_Sek.nextval, 'konserwator', 'monitorowanie stanu instalacji technicnych, usuwanie awarii');
INSERT INTO Stanowiska VALUES(Stanowiska_ID_Sek.nextval, 'ksiegowa', 'ksiegowanie faktur, przygotowywanie przelewow');
INSERT INTO Stanowiska VALUES(Stanowiska_ID_Sek.nextval, 'inspektor BHP', 'znajomosc zasad BHP i PPOZ');
INSERT INTO Stanowiska VALUES(Stanowiska_ID_Sek.nextval, 'sprzataczka', 'utrzymywanie porzadku');

INSERT INTO Pracownicy VALUES(Pracownicy_ID_Sek.nextval, 16, 16, sysdate - 1158, 10000, 'dobry', sysdate + 79, '0', '');
INSERT INTO Pracownicy VALUES(Pracownicy_ID_Sek.nextval, 17, 16, sysdate - 2212, 6000, 'dobry', sysdate + 239, '0', '');
INSERT INTO Pracownicy VALUES(Pracownicy_ID_Sek.nextval, 18, 17, sysdate - -50, 2500, 'dobry', sysdate + 322, '1', '');
INSERT INTO Pracownicy VALUES(Pracownicy_ID_Sek.nextval, 19, 17, sysdate - 261, 2800, 'dobry', sysdate + 313, '0', '');
INSERT INTO Pracownicy VALUES(Pracownicy_ID_Sek.nextval, 20, 22, sysdate - 1165, 2200, 'dobry', sysdate + 187, '1', '');
INSERT INTO Pracownicy VALUES(Pracownicy_ID_Sek.nextval, 21, 17, sysdate - 544, 3000, 'dobry', sysdate + 47, '1', '');
INSERT INTO Pracownicy VALUES(Pracownicy_ID_Sek.nextval, 22, 16, sysdate - 2209, 4000, 'dobry', sysdate + 166, '1', '');
INSERT INTO Pracownicy VALUES(Pracownicy_ID_Sek.nextval, 23, 17, sysdate - 982, 3000, 'dobry', sysdate + 229, '1', '');
INSERT INTO Pracownicy VALUES(Pracownicy_ID_Sek.nextval, 24, 17, sysdate - 2665, 3500, 'dobry', sysdate + 72, '0', '');
INSERT INTO Pracownicy VALUES(Pracownicy_ID_Sek.nextval, 25, 16, sysdate - 931, 4000, 'dobry', sysdate + 304, '1', '');
INSERT INTO Pracownicy VALUES(Pracownicy_ID_Sek.nextval, 26, 17, sysdate - 1336, 1600, 'dobry', sysdate + 69, '1', '');
INSERT INTO Pracownicy VALUES(Pracownicy_ID_Sek.nextval, 27, 23, sysdate - -154, 3200, 'dobry', sysdate + 86, '0', '');
INSERT INTO Pracownicy VALUES(Pracownicy_ID_Sek.nextval, 28, 16, sysdate - 1497, 3500, 'dobry', sysdate + 66, '1', '');
INSERT INTO Pracownicy VALUES(Pracownicy_ID_Sek.nextval, 29, 16, sysdate - 1820, 4000, 'dobry', sysdate + 173, '0', '');
INSERT INTO Pracownicy VALUES(Pracownicy_ID_Sek.nextval, 30, 23, sysdate - 1474, 1500, 'dobry', sysdate + 191, '0', '');

INSERT INTO Stanowiska_pracownikow VALUES(Stanowiska_pracownikow_ID_Sek.nextval, 1, 1);
INSERT INTO Stanowiska_pracownikow VALUES(Stanowiska_pracownikow_ID_Sek.nextval, 2, 2);
INSERT INTO Stanowiska_pracownikow VALUES(Stanowiska_pracownikow_ID_Sek.nextval, 3, 3);
INSERT INTO Stanowiska_pracownikow VALUES(Stanowiska_pracownikow_ID_Sek.nextval, 4, 4);
INSERT INTO Stanowiska_pracownikow VALUES(Stanowiska_pracownikow_ID_Sek.nextval, 5, 5);
INSERT INTO Stanowiska_pracownikow VALUES(Stanowiska_pracownikow_ID_Sek.nextval, 6, 6);
INSERT INTO Stanowiska_pracownikow VALUES(Stanowiska_pracownikow_ID_Sek.nextval, 7, 7);
INSERT INTO Stanowiska_pracownikow VALUES(Stanowiska_pracownikow_ID_Sek.nextval, 8, 8);
INSERT INTO Stanowiska_pracownikow VALUES(Stanowiska_pracownikow_ID_Sek.nextval, 9, 9);
INSERT INTO Stanowiska_pracownikow VALUES(Stanowiska_pracownikow_ID_Sek.nextval, 10, 10);
INSERT INTO Stanowiska_pracownikow VALUES(Stanowiska_pracownikow_ID_Sek.nextval, 11, 11);
INSERT INTO Stanowiska_pracownikow VALUES(Stanowiska_pracownikow_ID_Sek.nextval, 12, 12);
INSERT INTO Stanowiska_pracownikow VALUES(Stanowiska_pracownikow_ID_Sek.nextval, 13, 13);
INSERT INTO Stanowiska_pracownikow VALUES(Stanowiska_pracownikow_ID_Sek.nextval, 14, 14);
INSERT INTO Stanowiska_pracownikow VALUES(Stanowiska_pracownikow_ID_Sek.nextval, 15, 15);

INSERT INTO Kategorie_produktow VALUES(Kategorie_produktow_ID_Sek.nextval, 'szafy', 'Mebel wolnostojacy lub zabudowany we wnece sciany, zamykany drzwiami, uzywany do przechowywania roznych przedmiotow, takich jak ubrania, ksiazki czy naczynia', '1');
INSERT INTO Kategorie_produktow VALUES(Kategorie_produktow_ID_Sek.nextval, 'komody', 'Mebel skrzyniowy z szufladami oraz drzwiczkami do przechowywania odziezy.', '1');
INSERT INTO Kategorie_produktow VALUES(Kategorie_produktow_ID_Sek.nextval, 'regaly', 'Mebel skladajacy sie z wielu polek, zamkniety lub otwarty', '0');
INSERT INTO Kategorie_produktow VALUES(Kategorie_produktow_ID_Sek.nextval, 'materace', 'Podklad miekki, a jednoczesnie sprezysty, podnoszacy komfort snu w lozku', '0');
INSERT INTO Kategorie_produktow VALUES(Kategorie_produktow_ID_Sek.nextval, 'krzesla', 'Mebel sluzacy do siedzenia, majacy z tylu oparcie', '0');
INSERT INTO Kategorie_produktow VALUES(Kategorie_produktow_ID_Sek.nextval, 'sofy', 'Niska, miekka kanapa', '1');
INSERT INTO Kategorie_produktow VALUES(Kategorie_produktow_ID_Sek.nextval, 'pufy', 'Miekki, niski taboret obity calkowicie tkanina lub skora', '0');
INSERT INTO Kategorie_produktow VALUES(Kategorie_produktow_ID_Sek.nextval, 'polki', 'Pozioma deska lub plyta umieszczona w szafie lub przytwierdzona do sciany, przeznaczona do ukladania na niej roznych rzeczy', '0');
INSERT INTO Kategorie_produktow VALUES(Kategorie_produktow_ID_Sek.nextval, 'stelaze', 'Stelaz lozka, nazywany rowniez rama lozka podtrzymuje materac', '0');
INSERT INTO Kategorie_produktow VALUES(Kategorie_produktow_ID_Sek.nextval, 'meble biurowe', 'Zestawy mebli do biur, w ich sklad wchodza: krzesla biurowe, szafki z zamkami, regaly, komody itp.', '0');
INSERT INTO Kategorie_produktow VALUES(Kategorie_produktow_ID_Sek.nextval, 'tapczany', 'Mebel do spania skladajacy sie z prostokatnego, drewnianego pudla oraz materaca', '1');
INSERT INTO Kategorie_produktow VALUES(Kategorie_produktow_ID_Sek.nextval, 'biurka', 'Mebel skrzyniowy z szufladami, szafkami i skrytkami, przy ktorym sie pisze, pracuje', '1');
INSERT INTO Kategorie_produktow VALUES(Kategorie_produktow_ID_Sek.nextval, 'mebloscianki', 'Skladaja sie z kilku segmentow meblowych, ze wzgledow oszczednosciowych posiadajacych wspolne elementy pionowe - scianki boczne', '1');
INSERT INTO Kategorie_produktow VALUES(Kategorie_produktow_ID_Sek.nextval, 'lustra', 'gladka powierzchnia odbijajaca swiatlo', '0');
INSERT INTO Kategorie_produktow VALUES(Kategorie_produktow_ID_Sek.nextval, 'akcesoria meblowe', 'akcesoria takie jak: oswietlenie LED, koce, poduszki, sztucce itp.', '0');

INSERT INTO Producenci VALUES(Producenci_ID_Sek.nextval, 'BRW');
INSERT INTO Producenci VALUES(Producenci_ID_Sek.nextval, 'FORTE');
INSERT INTO Producenci VALUES(Producenci_ID_Sek.nextval, 'KOLO');
INSERT INTO Producenci VALUES(Producenci_ID_Sek.nextval, 'MARKOS');
INSERT INTO Producenci VALUES(Producenci_ID_Sek.nextval, 'MATERASSO');
INSERT INTO Producenci VALUES(Producenci_ID_Sek.nextval, 'SZYNAKA');
INSERT INTO Producenci VALUES(Producenci_ID_Sek.nextval, 'SIGNAL');
INSERT INTO Producenci VALUES(Producenci_ID_Sek.nextval, 'AGATA');
INSERT INTO Producenci VALUES(Producenci_ID_Sek.nextval, 'VOX');
INSERT INTO Producenci VALUES(Producenci_ID_Sek.nextval, 'DEK');
INSERT INTO Producenci VALUES(Producenci_ID_Sek.nextval, 'KFM');
INSERT INTO Producenci VALUES(Producenci_ID_Sek.nextval, 'MEBLEJANA');
INSERT INTO Producenci VALUES(Producenci_ID_Sek.nextval, 'IKEA');
INSERT INTO Producenci VALUES(Producenci_ID_Sek.nextval, 'JYSK');
INSERT INTO Producenci VALUES(Producenci_ID_Sek.nextval, 'ABRA');

INSERT INTO Lokalizacje_produktow VALUES(Lokalizacje_produktow_ID_Sek.nextval, 'Hala glowna', '4', '');
INSERT INTO Lokalizacje_produktow VALUES(Lokalizacje_produktow_ID_Sek.nextval, 'Meble biurowe', '38', '');
INSERT INTO Lokalizacje_produktow VALUES(Lokalizacje_produktow_ID_Sek.nextval, 'Meble dzieciece', '48', '');
INSERT INTO Lokalizacje_produktow VALUES(Lokalizacje_produktow_ID_Sek.nextval, 'Dekoracje', '33', '');
INSERT INTO Lokalizacje_produktow VALUES(Lokalizacje_produktow_ID_Sek.nextval, 'Sypialnie', '19', '');
INSERT INTO Lokalizacje_produktow VALUES(Lokalizacje_produktow_ID_Sek.nextval, 'Biuro', '32', '');
INSERT INTO Lokalizacje_produktow VALUES(Lokalizacje_produktow_ID_Sek.nextval, 'Lozka/materace', '31', '');
INSERT INTO Lokalizacje_produktow VALUES(Lokalizacje_produktow_ID_Sek.nextval, 'Kuchnia', '36', '');
INSERT INTO Lokalizacje_produktow VALUES(Lokalizacje_produktow_ID_Sek.nextval, 'Wypoczynki', '37', '');
INSERT INTO Lokalizacje_produktow VALUES(Lokalizacje_produktow_ID_Sek.nextval, 'Magazyn', '46', '');
INSERT INTO Lokalizacje_produktow VALUES(Lokalizacje_produktow_ID_Sek.nextval, 'Hala sprzedazowa 1', '26', '');
INSERT INTO Lokalizacje_produktow VALUES(Lokalizacje_produktow_ID_Sek.nextval, 'Hala sprzedazowa 2', '44', '');
INSERT INTO Lokalizacje_produktow VALUES(Lokalizacje_produktow_ID_Sek.nextval, 'Hala sprzedazowa 3', '7', '');
INSERT INTO Lokalizacje_produktow VALUES(Lokalizacje_produktow_ID_Sek.nextval, 'Salon firmowy A', '5', '');
INSERT INTO Lokalizacje_produktow VALUES(Lokalizacje_produktow_ID_Sek.nextval, 'Salon firmowy B', '29', '');

INSERT INTO Produkty VALUES(Produkty_ID_Sek.nextval, 1, 1, 1, '1111133917', 'Szafex', 'Szafa 3 drzwiowa z lustrem, dostepna w 3 kolorach', 1300, 6, '23', '2021', 10, 20);
INSERT INTO Produkty VALUES(Produkty_ID_Sek.nextval, 2, 2, 2, '1111129391', 'Komodex', 'Komoda 2 drzwi - 3 szuflady , dostepna w 5 kolorach', 500, 1, '23', '2019', 67, 17);
INSERT INTO Produkty VALUES(Produkty_ID_Sek.nextval, 3, 3, 3, '1111138485', 'Regalix', 'Regal otwarty 5 polek, dostepny w 3 kolorach', 700, 3, '23', '2020', 71, 19);
INSERT INTO Produkty VALUES(Produkty_ID_Sek.nextval, 4, 4, 4, '1111114912', 'Materacex', 'Materac piankowy 120x200 cm', 200, 9, '23', '2019', 38, 36);
INSERT INTO Produkty VALUES(Produkty_ID_Sek.nextval, 5, 5, 5, '1111123621', 'Krzeslix', 'Krzeslo z tapicerowanym siedziskiem oraz oparciem, stelaz dostepny w 3 kolorach, tapicerka w 20, w tym eko-skora', 120, 5, '23', '2019', 75, 11);
INSERT INTO Produkty VALUES(Produkty_ID_Sek.nextval, 6, 6, 6, '1111129289', 'Stolex', 'Taboret drewniany 40x40 cm dostepny w 10 kolorach', 50, 6, '23', '2021', 67, 30);
INSERT INTO Produkty VALUES(Produkty_ID_Sek.nextval, 7, 7, 7, '1111126517', 'Sofex', 'Sofa skorzana z funkcja spania', 2000, 2, '23', '2021', 29, 47);
INSERT INTO Produkty VALUES(Produkty_ID_Sek.nextval, 8, 8, 8, '1111126972', 'Pufix', 'Pufa typu worek, dostepna w 15 kolorach ', 300, 8, '23', '2020', 49, 16);
INSERT INTO Produkty VALUES(Produkty_ID_Sek.nextval, 9, 9, 9, '1111119324', 'Polex', 'Polka drewniana z podswietleniem LED, dostepna w 3 kolorach', 200, 7, '23', '2021', 47, 3);
INSERT INTO Produkty VALUES(Produkty_ID_Sek.nextval, 10, 10, 10, '1111138399', 'Stelazex', 'Stelaz lozkowy 200x160cm, amortyzowany', 250, 1, '23', '2021', 72, 30);
INSERT INTO Produkty VALUES(Produkty_ID_Sek.nextval, 11, 11, 11, '1111122785', 'Biurex', 'Krzeslo biurowe z regulowanym oparciem, dostepne w 5 kolorach', 300, 4, '23', '2020', 17, 15);
INSERT INTO Produkty VALUES(Produkty_ID_Sek.nextval, 12, 12, 12, '1111111662', 'Tapczix', 'Tapczan z pojemnikiem na posciel, dostepny w 4 wersjach kolorystycznych', 3500, 4, '23', '2020', 58, 10);
INSERT INTO Produkty VALUES(Produkty_ID_Sek.nextval, 13, 13, 13, '1111127924', 'Szufladzix', 'Komoda 5 szuflad, dostepna w 5 kolorach', 400, 4, '23', '2021', 24, 0);
INSERT INTO Produkty VALUES(Produkty_ID_Sek.nextval, 14, 14, 14, '1111112630', 'Biurkor', 'Biurko proste z szafka, szuflada oraz polka na klawiature. Dostepne w 2 kolorach', 2000, 5, '23', '2020', 63, 8);
INSERT INTO Produkty VALUES(Produkty_ID_Sek.nextval, 15, 15, 15, '1111111500', 'Lustix', 'Lustro ozdobne z oswietleniem LED', 120, 1, '23', '2020', 89, 25);

INSERT INTO Zamowienia VALUES(Zamowienia_ID_Sek.nextval, 1, sysdate - 236, '1', sysdate - 95, '1', sysdate - 36, '1', 1);
INSERT INTO Zamowienia VALUES(Zamowienia_ID_Sek.nextval, 2, sysdate - 208, '0', sysdate - 80, '1', sysdate - 29, '0', 2);
INSERT INTO Zamowienia VALUES(Zamowienia_ID_Sek.nextval, 3, sysdate - 151, '0', sysdate - 72, '0', sysdate - 34, '0', 3);
INSERT INTO Zamowienia VALUES(Zamowienia_ID_Sek.nextval, 4, sysdate - 164, '0', sysdate - 78, '1', sysdate - 37, '1', 4);
INSERT INTO Zamowienia VALUES(Zamowienia_ID_Sek.nextval, 5, sysdate - 209, '1', sysdate - 87, '0', sysdate - 28, '0', 5);
INSERT INTO Zamowienia VALUES(Zamowienia_ID_Sek.nextval, 6, sysdate - 175, '0', sysdate - 86, '0', sysdate - 35, '0', 6);
INSERT INTO Zamowienia VALUES(Zamowienia_ID_Sek.nextval, 7, sysdate - 119, '1', sysdate - 56, '0', sysdate - 32, '0', 7);
INSERT INTO Zamowienia VALUES(Zamowienia_ID_Sek.nextval, 8, sysdate - 297, '0', sysdate - 50, '1', sysdate - 36, '1', 8);
INSERT INTO Zamowienia VALUES(Zamowienia_ID_Sek.nextval, 9, sysdate - 194, '1', sysdate - 90, '1', sysdate - 26, '0', 9);
INSERT INTO Zamowienia VALUES(Zamowienia_ID_Sek.nextval, 10, sysdate - 140, '0', sysdate - 86, '0', sysdate - 43, '1', 10);
INSERT INTO Zamowienia VALUES(Zamowienia_ID_Sek.nextval, 11, sysdate - 109, '0', sysdate - 55, '0', sysdate - 37, '1', 11);
INSERT INTO Zamowienia VALUES(Zamowienia_ID_Sek.nextval, 12, sysdate - 297, '0', sysdate - 97, '0', sysdate - 41, '1', 12);
INSERT INTO Zamowienia VALUES(Zamowienia_ID_Sek.nextval, 13, sysdate - 261, '0', sysdate - 90, '1', sysdate - 45, '1', 13);
INSERT INTO Zamowienia VALUES(Zamowienia_ID_Sek.nextval, 14, sysdate - 282, '1', sysdate - 90, '0', sysdate - 33, '1', 14);
INSERT INTO Zamowienia VALUES(Zamowienia_ID_Sek.nextval, 15, sysdate - 249, '1', sysdate - 75, '1', sysdate - 35, '0', 15);

INSERT INTO Zamowienia_produkty VALUES(Zamowienia_produkty_ID_Sek.nextval, 1, 1, 1);
INSERT INTO Zamowienia_produkty VALUES(Zamowienia_produkty_ID_Sek.nextval, 2, 2, 9);
INSERT INTO Zamowienia_produkty VALUES(Zamowienia_produkty_ID_Sek.nextval, 3, 3, 7);
INSERT INTO Zamowienia_produkty VALUES(Zamowienia_produkty_ID_Sek.nextval, 4, 4, 10);
INSERT INTO Zamowienia_produkty VALUES(Zamowienia_produkty_ID_Sek.nextval, 5, 5, 10);
INSERT INTO Zamowienia_produkty VALUES(Zamowienia_produkty_ID_Sek.nextval, 6, 6, 4);
INSERT INTO Zamowienia_produkty VALUES(Zamowienia_produkty_ID_Sek.nextval, 7, 7, 6);
INSERT INTO Zamowienia_produkty VALUES(Zamowienia_produkty_ID_Sek.nextval, 8, 8, 4);
INSERT INTO Zamowienia_produkty VALUES(Zamowienia_produkty_ID_Sek.nextval, 9, 9, 1);
INSERT INTO Zamowienia_produkty VALUES(Zamowienia_produkty_ID_Sek.nextval, 10, 10, 1);
INSERT INTO Zamowienia_produkty VALUES(Zamowienia_produkty_ID_Sek.nextval, 11, 11, 8);
INSERT INTO Zamowienia_produkty VALUES(Zamowienia_produkty_ID_Sek.nextval, 12, 12, 6);
INSERT INTO Zamowienia_produkty VALUES(Zamowienia_produkty_ID_Sek.nextval, 13, 13, 9);
INSERT INTO Zamowienia_produkty VALUES(Zamowienia_produkty_ID_Sek.nextval, 14, 14, 4);
INSERT INTO Zamowienia_produkty VALUES(Zamowienia_produkty_ID_Sek.nextval, 15, 15, 9);

INSERT INTO Uslugi VALUES(Uslugi_ID_Sek.nextval, 'przeprowadzki', 'Pomoc w zmianie miejsca zamieszkania, noszenie mebli oraz innych artukulow', 400, 23);
INSERT INTO Uslugi VALUES(Uslugi_ID_Sek.nextval, 'pelny montaz', 'Sprawdzenie stanu, rozpakowanie, montaz mebli', 200, 23);
INSERT INTO Uslugi VALUES(Uslugi_ID_Sek.nextval, 'dojazd - strefa 1', 'Dojazd do klienta na terenie miasta Kielce', 50, 23);
INSERT INTO Uslugi VALUES(Uslugi_ID_Sek.nextval, 'dojazd - strefa 2', 'Dojazd do klienta poza miastem Kielce', 120, 23);
INSERT INTO Uslugi VALUES(Uslugi_ID_Sek.nextval, 'wniesienie', 'Wniesienie paczek lub zmontowanych mebli', 50, 23);
INSERT INTO Uslugi VALUES(Uslugi_ID_Sek.nextval, 'zniesienie', 'Wyniesienie starych mebli', 50, 23);
INSERT INTO Uslugi VALUES(Uslugi_ID_Sek.nextval, 'ustawienie mebli', 'Ustawienie zgodnie z projektem lub zyczeniem klienta', 30, 23);
INSERT INTO Uslugi VALUES(Uslugi_ID_Sek.nextval, 'sprzatanie', 'Wywoz elementow zabezpieczajacych i opakowan', 20, 23);
INSERT INTO Uslugi VALUES(Uslugi_ID_Sek.nextval, 'montaz luster/obrazow', 'Przygotowanie sciany do wiercenia, powieszenie luster lub innych elementow dekoracyjnych oraz ich wypoziomowanie', 40, 23);
INSERT INTO Uslugi VALUES(Uslugi_ID_Sek.nextval, 'docinanie', 'Docinanie mebli pod wymiar', 2630, 23);
INSERT INTO Uslugi VALUES(Uslugi_ID_Sek.nextval, 'serwis', 'Serwisowanie mebli, naprawa spuchnietych plyt wiorowych, naprawa rys i wglebien, oklejanie fornirem, poziomowanie drzwiczek', 70, 23);
INSERT INTO Uslugi VALUES(Uslugi_ID_Sek.nextval, 'planowanie kuchni', 'Szkic kuchni wraz z wycena w tym montaz i transport, pelen projekt 3D, wymiarowanie pomieszczenia', 300, 23);
INSERT INTO Uslugi VALUES(Uslugi_ID_Sek.nextval, 'projektowanie wnetrz', 'Projekt 3D pomieszczen mieszkalnych, koloze produktowe, dopasowanie kolorystyki scian i podlog', 400, 23);
INSERT INTO Uslugi VALUES(Uslugi_ID_Sek.nextval, 'projektowanie dla firm', 'Aranzacja wnetrza firmowego, w tym wymiarowanie, produkcja lub przeprowadzenie zamowienia mebli na wymiar, doradztwo materialowe', 1000, 23);
INSERT INTO Uslugi VALUES(Uslugi_ID_Sek.nextval, 'montaz sprzetu AGD i RTV', 'Montaz sprzetu elektronicznego oraz artukulow gospodarstwa domowego', 230, 23);

INSERT INTO Zlecenia_uslug VALUES(Zlecenia_uslug_ID_Sek.nextval, 1, 1, sysdate - 295,  '1', sysdate - 60, '1', sysdate + 45);
INSERT INTO Zlecenia_uslug VALUES(Zlecenia_uslug_ID_Sek.nextval, 2, 2, sysdate - 291,  '1', sysdate - 66, '1', sysdate + 48);
INSERT INTO Zlecenia_uslug VALUES(Zlecenia_uslug_ID_Sek.nextval, 3, 3, sysdate - 127,  '0', sysdate - 69, '1', sysdate + 48);
INSERT INTO Zlecenia_uslug VALUES(Zlecenia_uslug_ID_Sek.nextval, 4, 4, sysdate - 237,  '0', sysdate - 96, '0', sysdate + 36);
INSERT INTO Zlecenia_uslug VALUES(Zlecenia_uslug_ID_Sek.nextval, 5, 5, sysdate - 108,  '1', sysdate - 76, '0', sysdate + 39);
INSERT INTO Zlecenia_uslug VALUES(Zlecenia_uslug_ID_Sek.nextval, 6, 6, sysdate - 234,  '1', sysdate - 90, '1', sysdate + 30);
INSERT INTO Zlecenia_uslug VALUES(Zlecenia_uslug_ID_Sek.nextval, 7, 7, sysdate - 205,  '0', sysdate - 74, '1', sysdate + 46);
INSERT INTO Zlecenia_uslug VALUES(Zlecenia_uslug_ID_Sek.nextval, 8, 8, sysdate - 160,  '1', sysdate - 52, '1', sysdate + 41);
INSERT INTO Zlecenia_uslug VALUES(Zlecenia_uslug_ID_Sek.nextval, 9, 9, sysdate - 202,  '0', sysdate - 85, '1', sysdate + 42);
INSERT INTO Zlecenia_uslug VALUES(Zlecenia_uslug_ID_Sek.nextval, 10, 10, sysdate - 132,  '0', sysdate - 51, '0', sysdate + 39);
INSERT INTO Zlecenia_uslug VALUES(Zlecenia_uslug_ID_Sek.nextval, 11, 11, sysdate - 207,  '0', sysdate - 57, '1', sysdate + 33);
INSERT INTO Zlecenia_uslug VALUES(Zlecenia_uslug_ID_Sek.nextval, 12, 12, sysdate - 251,  '0', sysdate - 89, '0', sysdate + 37);
INSERT INTO Zlecenia_uslug VALUES(Zlecenia_uslug_ID_Sek.nextval, 13, 13, sysdate - 116,  '1', sysdate - 75, '1', sysdate + 39);
INSERT INTO Zlecenia_uslug VALUES(Zlecenia_uslug_ID_Sek.nextval, 14, 14, sysdate - 232,  '0', sysdate - 68, '1', sysdate + 33);
INSERT INTO Zlecenia_uslug VALUES(Zlecenia_uslug_ID_Sek.nextval, 15, 15, sysdate - 254,  '0', sysdate - 96, '0', sysdate + 34);

INSERT INTO Pracownicy_zlecen VALUES(Pracownicy_zlecen_ID_Sek.nextval, 4, 1);
INSERT INTO Pracownicy_zlecen VALUES(Pracownicy_zlecen_ID_Sek.nextval, 4, 2);
INSERT INTO Pracownicy_zlecen VALUES(Pracownicy_zlecen_ID_Sek.nextval, 5, 3);
INSERT INTO Pracownicy_zlecen VALUES(Pracownicy_zlecen_ID_Sek.nextval, 5, 4);
INSERT INTO Pracownicy_zlecen VALUES(Pracownicy_zlecen_ID_Sek.nextval, 2, 5);
INSERT INTO Pracownicy_zlecen VALUES(Pracownicy_zlecen_ID_Sek.nextval, 2, 6);
INSERT INTO Pracownicy_zlecen VALUES(Pracownicy_zlecen_ID_Sek.nextval, 7, 7);
INSERT INTO Pracownicy_zlecen VALUES(Pracownicy_zlecen_ID_Sek.nextval, 15, 8);
INSERT INTO Pracownicy_zlecen VALUES(Pracownicy_zlecen_ID_Sek.nextval, 4, 9);
INSERT INTO Pracownicy_zlecen VALUES(Pracownicy_zlecen_ID_Sek.nextval, 12, 10);
INSERT INTO Pracownicy_zlecen VALUES(Pracownicy_zlecen_ID_Sek.nextval, 8, 11);
INSERT INTO Pracownicy_zlecen VALUES(Pracownicy_zlecen_ID_Sek.nextval, 9, 12);
INSERT INTO Pracownicy_zlecen VALUES(Pracownicy_zlecen_ID_Sek.nextval, 6, 13);
INSERT INTO Pracownicy_zlecen VALUES(Pracownicy_zlecen_ID_Sek.nextval, 6, 14);
INSERT INTO Pracownicy_zlecen VALUES(Pracownicy_zlecen_ID_Sek.nextval, 4, 15);
