CREATE SEQUENCE Adresy_ID_Sek START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE Osoby_ID_Sek START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE Klienci_ID_Sek START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE Stanowiska_ID_Sek START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE Pracownicy_ID_Sek START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE Stanowiska_pracownikow_ID_Sek START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE Kategorie_produktow_ID_Sek START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE Producenci_ID_Sek START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE Lokalizacje_produktow_ID_Sek START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE Produkty_ID_Sek START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE Zamowienia_ID_Sek START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE Zamowienia_produkty_ID_Sek START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE Uslugi_ID_Sek START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE Zlecenia_uslug_ID_Sek START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE Pracownicy_zlecen_ID_Sek START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

INSERT INTO Adresy VALUES(Adresy_ID_Sek.nextval, 'Kielce', 'Świętokrzyska', '92', '14');
INSERT INTO Adresy VALUES(Adresy_ID_Sek.nextval, 'Chęciny', 'Szkolna', '91', '24');
INSERT INTO Adresy VALUES(Adresy_ID_Sek.nextval, 'Stąporków', 'Chopina', '80', '10');
INSERT INTO Adresy VALUES(Adresy_ID_Sek.nextval, 'Morawica', 'Niebieska', '62', '42');
INSERT INTO Adresy VALUES(Adresy_ID_Sek.nextval, 'Cedzyna', 'Kielecka', '64', '28');
INSERT INTO Adresy VALUES(Adresy_ID_Sek.nextval, 'Ciekoty', 'Parcela', '113', '25');
INSERT INTO Adresy VALUES(Adresy_ID_Sek.nextval, 'Kostomłoty', 'Maciejówka', '81', '12');
INSERT INTO Adresy VALUES(Adresy_ID_Sek.nextval, 'Piekoszów', 'Wolności', '48', '44');
INSERT INTO Adresy VALUES(Adresy_ID_Sek.nextval, 'Daleszyce', 'Sienkiewicza', '41', '56');
INSERT INTO Adresy VALUES(Adresy_ID_Sek.nextval, 'Krajno', 'Pogorzele', '122', '49');
INSERT INTO Adresy VALUES(Adresy_ID_Sek.nextval, 'Mniów', 'Gajowa', '23', '45');
INSERT INTO Adresy VALUES(Adresy_ID_Sek.nextval, 'Gliniany Las', 'Kościelna', '19', '27');
INSERT INTO Adresy VALUES(Adresy_ID_Sek.nextval, 'Chańcza', 'Zalewska', '33', '56');
INSERT INTO Adresy VALUES(Adresy_ID_Sek.nextval, 'Makoszyn', 'Wiejska', '132', '55');
INSERT INTO Adresy VALUES(Adresy_ID_Sek.nextval, 'Górno', 'Dolna', '96', '33');
INSERT INTO Adresy VALUES(Adresy_ID_Sek.nextval, 'Kraków', 'Krakowska', '36', '49');
INSERT INTO Adresy VALUES(Adresy_ID_Sek.nextval, 'Warszawa', 'Warszawska', '103', '17');
INSERT INTO Adresy VALUES(Adresy_ID_Sek.nextval, 'Wrocław', 'Wrocławska', '26', '33');
INSERT INTO Adresy VALUES(Adresy_ID_Sek.nextval, 'Poznań', 'Poznańska', '38', '59');
INSERT INTO Adresy VALUES(Adresy_ID_Sek.nextval, 'Lublin', 'Lublińska', '2', '30');
INSERT INTO Adresy VALUES(Adresy_ID_Sek.nextval, 'Zamość', 'Zamożna', '34', '32');
INSERT INTO Adresy VALUES(Adresy_ID_Sek.nextval, 'Gdynia', 'Gdyńska', '125', '57');
INSERT INTO Adresy VALUES(Adresy_ID_Sek.nextval, 'Gdańsk', 'Gdańska', '140', '36');
INSERT INTO Adresy VALUES(Adresy_ID_Sek.nextval, 'Sopot', 'Sopocka', '146', '8');
INSERT INTO Adresy VALUES(Adresy_ID_Sek.nextval, 'Częstochowa', 'Częstochowska', '2', '19');
INSERT INTO Adresy VALUES(Adresy_ID_Sek.nextval, 'Białystok', 'Białostocka', '145', '44');
INSERT INTO Adresy VALUES(Adresy_ID_Sek.nextval, 'Łódź', 'Łódzka', '39', '39');
INSERT INTO Adresy VALUES(Adresy_ID_Sek.nextval, 'Bydgoszcz', 'Śmieciowa', '142', '1');
INSERT INTO Adresy VALUES(Adresy_ID_Sek.nextval, 'Szczecin', 'Szczecińska', '46', '32');
INSERT INTO Adresy VALUES(Adresy_ID_Sek.nextval, 'Katowice', 'Katowicka', '126', '2');

INSERT INTO Osoby VALUES(Osoby_ID_Sek.nextval, 1, 'Kristina', 'Valevska', sysdate - 30148, '11111137835', '111129952', 'k.valevska@gmail.com', 'K');
INSERT INTO Osoby VALUES(Osoby_ID_Sek.nextval, 2, 'Ewa', 'Braun', sysdate - 28759, '11111116366', '111112691', 'e.braun@gmail.com', 'K');
INSERT INTO Osoby VALUES(Osoby_ID_Sek.nextval, 3, 'Anna', 'Zalewska', sysdate - 31226, '11111140450', '111115146', 'a.zalewska@gmail.com', 'K');
INSERT INTO Osoby VALUES(Osoby_ID_Sek.nextval, 4, 'Teresa', 'Ostrowska', sysdate - 29515, '11111143804', '111114023', 't.ostrowska@gmail.com', 'K');
INSERT INTO Osoby VALUES(Osoby_ID_Sek.nextval, 5, 'Halina', 'Kwiatkowska', sysdate - 11652, '11111129655', '111115033', 'h.kwiatkowska@gmail.com', 'K');
INSERT INTO Osoby VALUES(Osoby_ID_Sek.nextval, 6, 'Igor', 'Kowalski', sysdate - 31321, '11111127174', '111119699', 'i.kowalski@gmail.com', 'M');
INSERT INTO Osoby VALUES(Osoby_ID_Sek.nextval, 7, 'Jacek', 'Nowak', sysdate - 33156, '11111133572', '111132329', 'j.nowak@gmail.com', 'M');
INSERT INTO Osoby VALUES(Osoby_ID_Sek.nextval, 8, 'Szymon', 'Kołodziejczyk', sysdate - 8481, '11111120422', '111133548', 's.kolodziejczyk@gmail.com', 'M');
INSERT INTO Osoby VALUES(Osoby_ID_Sek.nextval, 9, 'Michał ', 'Kwaczor', sysdate - 19374, '11111131524', '111116171', 'm.kwaczor@gmail.com', 'M');
INSERT INTO Osoby VALUES(Osoby_ID_Sek.nextval, 10, 'Paweł', 'Piotrowski', sysdate - 24246, '11111142417', '111142792', 'p.piotrowski@gmail.com', 'M');
INSERT INTO Osoby VALUES(Osoby_ID_Sek.nextval, 11, 'Jakub', 'Kotwica', sysdate - 30752, '11111135943', '111142232', 'j.kotwica@gmail.com', 'M');
INSERT INTO Osoby VALUES(Osoby_ID_Sek.nextval, 12, 'Bartłomiej', 'Bugara', sysdate - 18533, '11111124510', '111114989', 'b.bugara@gmail.com', 'M');
INSERT INTO Osoby VALUES(Osoby_ID_Sek.nextval, 13, 'Janusz', 'Gajos', sysdate - 33964, '11111128777', '111116994', 'j.gajos@gmail.com', 'M');
INSERT INTO Osoby VALUES(Osoby_ID_Sek.nextval, 14, 'Tomasz', 'Rak', sysdate - 24767, '11111124141', '111139918', 't.rak@gmail.com', 'M');
INSERT INTO Osoby VALUES(Osoby_ID_Sek.nextval, 15, 'Maciej', 'Kozłowski', sysdate - 11713, '11111124676', '111114370', 'm.kozlowski@gmail.com', 'M');
INSERT INTO Osoby VALUES(Osoby_ID_Sek.nextval, 16, 'Ireneusz', 'Krupa', sysdate - 13150, '11111119357', '111126311', 'i.krupa@gmail.com', 'M');
INSERT INTO Osoby VALUES(Osoby_ID_Sek.nextval, 17, 'Gracjan', 'Głowacki', sysdate - 6894, '11111121182', '111127225', 'g.glowacki@gmail.com', 'M');
INSERT INTO Osoby VALUES(Osoby_ID_Sek.nextval, 18, 'Marcin', 'Jankowski', sysdate - 24866, '11111133976', '111116547', 'm.jankowski@gmail.com', 'M');
INSERT INTO Osoby VALUES(Osoby_ID_Sek.nextval, 19, 'Mateusz', 'Chmielewski', sysdate - 35767, '11111126232', '111131091', 'm.chmielewski@gmail.com', 'M');
INSERT INTO Osoby VALUES(Osoby_ID_Sek.nextval, 20, 'Kordian', 'Sikora', sysdate - 32609, '11111118490', '111139100', 'k.sikora@gmail.com', 'M');
INSERT INTO Osoby VALUES(Osoby_ID_Sek.nextval, 21, 'Ignacy', 'Witkowski', sysdate - 9067, '11111142946', '111125418', 'i.witkowski@gmail.com', 'M');
INSERT INTO Osoby VALUES(Osoby_ID_Sek.nextval, 22, 'Cyprian', 'Cieślak', sysdate - 25634, '11111112551', '111140843', 'c.cieslak@gmail.com', 'M');
INSERT INTO Osoby VALUES(Osoby_ID_Sek.nextval, 23, 'Ariel', 'Kalinowski', sysdate - 14394, '11111142743', '111132928', 'a.kalinowski@gmail.com', 'M');
INSERT INTO Osoby VALUES(Osoby_ID_Sek.nextval, 24, 'Kornel', 'Malinowski', sysdate - 16288, '11111130446', '111127662', 'k.malinowski@gmail.com', 'M');
INSERT INTO Osoby VALUES(Osoby_ID_Sek.nextval, 25, 'Janusz', 'Brzeziński', sysdate - 33256, '11111140621', '111129721', 'j.brzezinski@gmail.com', 'M');
INSERT INTO Osoby VALUES(Osoby_ID_Sek.nextval, 26, 'Irena', 'Szymczak', sysdate - 19128, '11111117649', '111121630', 'i.szymczak@gmail.com', 'K');
INSERT INTO Osoby VALUES(Osoby_ID_Sek.nextval, 27, 'Izyda', 'Jankowska', sysdate - 28679, '11111133116', '111123242', 'i.jankowska@gmail.com', 'K');
INSERT INTO Osoby VALUES(Osoby_ID_Sek.nextval, 28, 'Maja', 'Włodarczyk', sysdate - 10451, '11111114591', '111132416', 'm.wlodarczyk@gmail.com', 'K');
INSERT INTO Osoby VALUES(Osoby_ID_Sek.nextval, 29, 'Alina', 'Mazur', sysdate - 19110, '11111141684', '111111587', 'a.mazur@gmail.com', 'K');
INSERT INTO Osoby VALUES(Osoby_ID_Sek.nextval, 30, 'Eliza', 'Maciejewska', sysdate - 11303, '11111124741', '111136130', 'e.maciejewska@gmail.com', 'K');

INSERT INTO Klienci VALUES(Klienci_ID_Sek.nextval, 1, sysdate - 418, '', '');
INSERT INTO Klienci VALUES(Klienci_ID_Sek.nextval, 2, sysdate - 1078, '', '');
INSERT INTO Klienci VALUES(Klienci_ID_Sek.nextval, 3, sysdate - 1852, '', '');
INSERT INTO Klienci VALUES(Klienci_ID_Sek.nextval, 4, sysdate - 455, '', '0123456789');
INSERT INTO Klienci VALUES(Klienci_ID_Sek.nextval, 5, sysdate - 1026, '', '');
INSERT INTO Klienci VALUES(Klienci_ID_Sek.nextval, 6, sysdate - 622, '', '');
INSERT INTO Klienci VALUES(Klienci_ID_Sek.nextval, 7, sysdate - 802, '', '');
INSERT INTO Klienci VALUES(Klienci_ID_Sek.nextval, 8, sysdate - 1372, '', '');
INSERT INTO Klienci VALUES(Klienci_ID_Sek.nextval, 9, sysdate - 1279, '', '9876543210');
INSERT INTO Klienci VALUES(Klienci_ID_Sek.nextval, 10, sysdate - 1027, '', '');
INSERT INTO Klienci VALUES(Klienci_ID_Sek.nextval, 11, sysdate - 819, '', '');
INSERT INTO Klienci VALUES(Klienci_ID_Sek.nextval, 12, sysdate - 1325, '', '');
INSERT INTO Klienci VALUES(Klienci_ID_Sek.nextval, 13, sysdate - 1409, '', '');
INSERT INTO Klienci VALUES(Klienci_ID_Sek.nextval, 14, sysdate - 666, '', '');
INSERT INTO Klienci VALUES(Klienci_ID_Sek.nextval, 15, sysdate - 1181, '', '');

INSERT INTO Stanowiska VALUES(Stanowiska_ID_Sek.nextval, 'prezes', 'zarządzanie firmą');
INSERT INTO Stanowiska VALUES(Stanowiska_ID_Sek.nextval, 'kierownik', 'zarządzanie pracą pracowników, kontrola czasu pracy');
INSERT INTO Stanowiska VALUES(Stanowiska_ID_Sek.nextval, 'sprzedawca', 'obsługa klientów');
INSERT INTO Stanowiska VALUES(Stanowiska_ID_Sek.nextval, 'monter', 'montaż mebli');
INSERT INTO Stanowiska VALUES(Stanowiska_ID_Sek.nextval, 'magazynier', 'monitorowanie stanów magazynowych');
INSERT INTO Stanowiska VALUES(Stanowiska_ID_Sek.nextval, 'doradca klienta', 'pomoc klientom w wyborze mebli');
INSERT INTO Stanowiska VALUES(Stanowiska_ID_Sek.nextval, 'logistyk', 'przygotowywanie przesyłek');
INSERT INTO Stanowiska VALUES(Stanowiska_ID_Sek.nextval, 'technik', 'serwisowanie sprzętu oraz jego konserwacja');
INSERT INTO Stanowiska VALUES(Stanowiska_ID_Sek.nextval, 'konsultant sprzedaży', 'negocjacje z klientami, znajomość oferty');
INSERT INTO Stanowiska VALUES(Stanowiska_ID_Sek.nextval, 'asystent', 'wspiera pracę prezesa oraz kierowników');
INSERT INTO Stanowiska VALUES(Stanowiska_ID_Sek.nextval, 'pracownik zewnętrzny', 'wykonuje zlecone mu zadania z danego zakresu');
INSERT INTO Stanowiska VALUES(Stanowiska_ID_Sek.nextval, 'konserwator', 'monitorowanie stanu instalacji technicnych, usuwanie awarii');
INSERT INTO Stanowiska VALUES(Stanowiska_ID_Sek.nextval, 'księgowa', 'księgowanie faktur, przygotowywanie przelewów');
INSERT INTO Stanowiska VALUES(Stanowiska_ID_Sek.nextval, 'inspektor BHP', 'znajomość zasad BHP i PPOŻ');
INSERT INTO Stanowiska VALUES(Stanowiska_ID_Sek.nextval, 'sprzątaczka', 'utrzymywanie porządku');

INSERT INTO Pracownicy VALUES(Pracownicy_ID_Sek.nextval, 16, 16, sysdate - 1158, 3342, 'dobry', sysdate + 79, '0', '');
INSERT INTO Pracownicy VALUES(Pracownicy_ID_Sek.nextval, 17, 16, sysdate - 2212, 3776, 'dobry', sysdate + 239, '0', '');
INSERT INTO Pracownicy VALUES(Pracownicy_ID_Sek.nextval, 18, 17, sysdate - -50, 2592, 'dobry', sysdate + 322, '1', '');
INSERT INTO Pracownicy VALUES(Pracownicy_ID_Sek.nextval, 19, 17, sysdate - 261, 3624, 'dobry', sysdate + 313, '0', '');
INSERT INTO Pracownicy VALUES(Pracownicy_ID_Sek.nextval, 20, 22, sysdate - 1165, 4572, 'dobry', sysdate + 187, '1', '');
INSERT INTO Pracownicy VALUES(Pracownicy_ID_Sek.nextval, 21, 17, sysdate - 544, 4334, 'dobry', sysdate + 47, '1', '');
INSERT INTO Pracownicy VALUES(Pracownicy_ID_Sek.nextval, 22, 16, sysdate - 2209, 4321, 'dobry', sysdate + 166, '1', '');
INSERT INTO Pracownicy VALUES(Pracownicy_ID_Sek.nextval, 23, 17, sysdate - 982, 3263, 'dobry', sysdate + 229, '1', '');
INSERT INTO Pracownicy VALUES(Pracownicy_ID_Sek.nextval, 24, 17, sysdate - 2665, 2475, 'dobry', sysdate + 72, '0', '');
INSERT INTO Pracownicy VALUES(Pracownicy_ID_Sek.nextval, 25, 16, sysdate - 931, 3390, 'dobry', sysdate + 304, '1', '');
INSERT INTO Pracownicy VALUES(Pracownicy_ID_Sek.nextval, 26, 17, sysdate - 1336, 2559, 'dobry', sysdate + 69, '1', '');
INSERT INTO Pracownicy VALUES(Pracownicy_ID_Sek.nextval, 27, 23, sysdate - -154, 3164, 'dobry', sysdate + 86, '0', '');
INSERT INTO Pracownicy VALUES(Pracownicy_ID_Sek.nextval, 28, 16, sysdate - 1497, 4111, 'dobry', sysdate + 66, '1', '');
INSERT INTO Pracownicy VALUES(Pracownicy_ID_Sek.nextval, 29, 16, sysdate - 1820, 3895, 'dobry', sysdate + 173, '0', '');
INSERT INTO Pracownicy VALUES(Pracownicy_ID_Sek.nextval, 30, 23, sysdate - 1474, 4232, 'dobry', sysdate + 191, '0', '');

INSERT INTO Stanowiska_pracownikow VALUES(Stanowiska_pracownikow_ID_Sek.nextval, 1, 1);
INSERT INTO Stanowiska_pracownikow VALUES(Stanowiska_pracownikow_ID_Sek.nextval, 2, 2);
INSERT INTO Stanowiska_pracownikow VALUES(Stanowiska_pracownikow_ID_Sek.nextval, 3, 3);
INSERT INTO Stanowiska_pracownikow VALUES(Stanowiska_pracownikow_ID_Sek.nextval, 4, 4);
INSERT INTO Stanowiska_pracownikow VALUES(Stanowiska_pracownikow_ID_Sek.nextval, 5, 5);
INSERT INTO Stanowiska_pracownikow VALUES(Stanowiska_pracownikow_ID_Sek.nextval, 6, 6);
INSERT INTO Stanowiska_pracownikow VALUES(Stanowiska_pracownikow_ID_Sek.nextval, 7, 7);
INSERT INTO Stanowiska_pracownikow VALUES(Stanowiska_pracownikow_ID_Sek.nextval, 8, 8);
INSERT INTO Stanowiska_pracownikow VALUES(Stanowiska_pracownikow_ID_Sek.nextval, 9, 9);
INSERT INTO Stanowiska_pracownikow VALUES(Stanowiska_pracownikow_ID_Sek.nextval, 10, 10);
INSERT INTO Stanowiska_pracownikow VALUES(Stanowiska_pracownikow_ID_Sek.nextval, 11, 11);
INSERT INTO Stanowiska_pracownikow VALUES(Stanowiska_pracownikow_ID_Sek.nextval, 12, 12);
INSERT INTO Stanowiska_pracownikow VALUES(Stanowiska_pracownikow_ID_Sek.nextval, 13, 13);
INSERT INTO Stanowiska_pracownikow VALUES(Stanowiska_pracownikow_ID_Sek.nextval, 14, 14);
INSERT INTO Stanowiska_pracownikow VALUES(Stanowiska_pracownikow_ID_Sek.nextval, 15, 15);

INSERT INTO Kategorie_produktow VALUES(Kategorie_produktow_ID_Sek.nextval, 'szafy', 'Mebel wolnostojący lub zabudowany we wnęce ściany, zamykany drzwiami, używany do przechowywania różnych przedmiotów, takich jak ubrania, książki czy naczynia', '1');
INSERT INTO Kategorie_produktow VALUES(Kategorie_produktow_ID_Sek.nextval, 'komody', 'Mebel skrzyniowy z szufladami oraz drzwiczkami do przechowywania odzieży.', '1');
INSERT INTO Kategorie_produktow VALUES(Kategorie_produktow_ID_Sek.nextval, 'regały', 'Mebel składający się z wielu półek, zamknięty lub otwarty', '0');
INSERT INTO Kategorie_produktow VALUES(Kategorie_produktow_ID_Sek.nextval, 'materace', 'Podkład miękki, a jednocześnie sprężysty, podnoszący komfort snu w łóżku', '0');
INSERT INTO Kategorie_produktow VALUES(Kategorie_produktow_ID_Sek.nextval, 'krzesła', 'Mebel służący do siedzenia, mający z tyłu oparcie', '0');
INSERT INTO Kategorie_produktow VALUES(Kategorie_produktow_ID_Sek.nextval, 'sofy', 'Niska, miękka kanapa', '1');
INSERT INTO Kategorie_produktow VALUES(Kategorie_produktow_ID_Sek.nextval, 'pufy', 'Miękki, niski taboret obity całkowicie tkaniną lub skórą', '0');
INSERT INTO Kategorie_produktow VALUES(Kategorie_produktow_ID_Sek.nextval, 'półki', 'Pozioma deska lub płyta umieszczona w szafie lub przytwierdzona do ściany, przeznaczona do układania na niej różnych rzeczy', '0');
INSERT INTO Kategorie_produktow VALUES(Kategorie_produktow_ID_Sek.nextval, 'stelaże', 'Stelaż łóżka, nazywany również ramą łóżka podtrzymuje materac', '0');
INSERT INTO Kategorie_produktow VALUES(Kategorie_produktow_ID_Sek.nextval, 'meble biurowe', 'Zestawy mebli do biur, w ich skład wchodzą: krzesła biurowe, szafki z zamkami, regały, komody itp.', '0');
INSERT INTO Kategorie_produktow VALUES(Kategorie_produktow_ID_Sek.nextval, 'tapczany', 'Mebel do spania składający się z prostokątnego, drewnianego pudła oraz materaca', '1');
INSERT INTO Kategorie_produktow VALUES(Kategorie_produktow_ID_Sek.nextval, 'biurka', 'Mebel skrzyniowy z szufladami, szafkami i skrytkami, przy którym się pisze, pracuje', '1');
INSERT INTO Kategorie_produktow VALUES(Kategorie_produktow_ID_Sek.nextval, 'meblościanki', 'Składają się z kilku segmentów meblowych, ze względów oszczędnościowych posiadających wspólne elementy pionowe - ścianki boczne', '1');
INSERT INTO Kategorie_produktow VALUES(Kategorie_produktow_ID_Sek.nextval, 'lustra', 'gładka powierzchnia odbijająca światło', '0');
INSERT INTO Kategorie_produktow VALUES(Kategorie_produktow_ID_Sek.nextval, 'akcesoria meblowe', 'akcesoria takie jak: oświetlenie LED, koce, poduszki, sztućce itp.', '0');

INSERT INTO Producenci VALUES(Producenci_ID_Sek.nextval, 'BRW');
INSERT INTO Producenci VALUES(Producenci_ID_Sek.nextval, 'FORTE');
INSERT INTO Producenci VALUES(Producenci_ID_Sek.nextval, 'KOŁO');
INSERT INTO Producenci VALUES(Producenci_ID_Sek.nextval, 'MARKOS');
INSERT INTO Producenci VALUES(Producenci_ID_Sek.nextval, 'MATERASSO');
INSERT INTO Producenci VALUES(Producenci_ID_Sek.nextval, 'SZYNAKA');
INSERT INTO Producenci VALUES(Producenci_ID_Sek.nextval, 'SIGNAL');
INSERT INTO Producenci VALUES(Producenci_ID_Sek.nextval, 'AGATA');
INSERT INTO Producenci VALUES(Producenci_ID_Sek.nextval, 'VOX');
INSERT INTO Producenci VALUES(Producenci_ID_Sek.nextval, 'DEK');
INSERT INTO Producenci VALUES(Producenci_ID_Sek.nextval, 'KFM');
INSERT INTO Producenci VALUES(Producenci_ID_Sek.nextval, 'MEBLEJANA');
INSERT INTO Producenci VALUES(Producenci_ID_Sek.nextval, 'IKEA');
INSERT INTO Producenci VALUES(Producenci_ID_Sek.nextval, 'JYSK');
INSERT INTO Producenci VALUES(Producenci_ID_Sek.nextval, 'ABRA');

INSERT INTO Lokalizacje_produktow VALUES(Lokalizacje_produktow_ID_Sek.nextval, 'Hala główna', '4', '');
INSERT INTO Lokalizacje_produktow VALUES(Lokalizacje_produktow_ID_Sek.nextval, 'Meble biurowe', '38', '');
INSERT INTO Lokalizacje_produktow VALUES(Lokalizacje_produktow_ID_Sek.nextval, 'Meble dzieciece', '48', '');
INSERT INTO Lokalizacje_produktow VALUES(Lokalizacje_produktow_ID_Sek.nextval, 'Dekoracje', '33', '');
INSERT INTO Lokalizacje_produktow VALUES(Lokalizacje_produktow_ID_Sek.nextval, 'Sypialnie', '19', '');
INSERT INTO Lokalizacje_produktow VALUES(Lokalizacje_produktow_ID_Sek.nextval, 'Biuro', '32', '');
INSERT INTO Lokalizacje_produktow VALUES(Lokalizacje_produktow_ID_Sek.nextval, 'Łózka/materace', '31', '');
INSERT INTO Lokalizacje_produktow VALUES(Lokalizacje_produktow_ID_Sek.nextval, 'Kuchnia', '36', '');
INSERT INTO Lokalizacje_produktow VALUES(Lokalizacje_produktow_ID_Sek.nextval, 'Wypoczynki', '37', '');
INSERT INTO Lokalizacje_produktow VALUES(Lokalizacje_produktow_ID_Sek.nextval, 'Magazyn', '46', '');
INSERT INTO Lokalizacje_produktow VALUES(Lokalizacje_produktow_ID_Sek.nextval, 'Hala sprzedażowa 1', '26', '');
INSERT INTO Lokalizacje_produktow VALUES(Lokalizacje_produktow_ID_Sek.nextval, 'Hala sprzedażowa 2', '44', '');
INSERT INTO Lokalizacje_produktow VALUES(Lokalizacje_produktow_ID_Sek.nextval, 'Hala sprzedażowa 3', '7', '');
INSERT INTO Lokalizacje_produktow VALUES(Lokalizacje_produktow_ID_Sek.nextval, 'Salon firmowy A', '5', '');
INSERT INTO Lokalizacje_produktow VALUES(Lokalizacje_produktow_ID_Sek.nextval, 'Salon firmowy B', '29', '');

INSERT INTO Produkty VALUES(Produkty_ID_Sek.nextval, 1, 1, 1, '1111133917', 'Szafex', 'Szafa 3 drzwiowa z lustrem, dostępna w 3 kolorach', 8108, 6, '23', '2021', 10, 20);
INSERT INTO Produkty VALUES(Produkty_ID_Sek.nextval, 2, 2, 2, '1111129391', 'Komodex', 'Komoda 2 drzwi - 3 szuflady , dostępna w 5 kolorach', 6644, 1, '23', '2019', 67, 17);
INSERT INTO Produkty VALUES(Produkty_ID_Sek.nextval, 3, 3, 3, '1111138485', 'Regalix', 'Regał otwarty 5 półek, dostepny w 3 kolorach', 2800, 3, '23', '2020', 71, 19);
INSERT INTO Produkty VALUES(Produkty_ID_Sek.nextval, 4, 4, 4, '1111114912', 'Materacex', 'Materac piankowy 120x200 cm', 17563, 9, '23', '2019', 38, 36);
INSERT INTO Produkty VALUES(Produkty_ID_Sek.nextval, 5, 5, 5, '1111123621', 'Krzesłix', 'Krzesło z tapicerowanym siedziskiem oraz oparciem, stelaż dostępny w 3 kolorach, tapicerka w 20, w tym eko-skóra', 2690, 5, '23', '2019', 75, 11);
INSERT INTO Produkty VALUES(Produkty_ID_Sek.nextval, 6, 6, 6, '1111129289', 'Stołex', 'Taboret drewniany 40x40 cm dostępny w 10 kolorach', 10970, 6, '23', '2021', 67, 30);
INSERT INTO Produkty VALUES(Produkty_ID_Sek.nextval, 7, 7, 7, '1111126517', 'Sofex', 'Sofa skórzana z funkcją spania', 3327, 2, '23', '2021', 29, 47);
INSERT INTO Produkty VALUES(Produkty_ID_Sek.nextval, 8, 8, 8, '1111126972', 'Pufix', 'Pufa typu worek, dostępna w 15 kolorach ', 3917, 8, '23', '2020', 49, 16);
INSERT INTO Produkty VALUES(Produkty_ID_Sek.nextval, 9, 9, 9, '1111119324', 'Półex', 'Półka drewniana z podswietleniem LED, dostępna w 3 kolorach', 5167, 7, '23', '2021', 47, 3);
INSERT INTO Produkty VALUES(Produkty_ID_Sek.nextval, 10, 10, 10, '1111138399', 'Stelażex', 'Stelaż łóżkowy 200x160cm, amortyzowany', 321, 1, '23', '2021', 72, 30);
INSERT INTO Produkty VALUES(Produkty_ID_Sek.nextval, 11, 11, 11, '1111122785', 'Biurex', 'Krzesło biurowe z regulowanym oparciem, dostępne w 5 kolorach', 16221, 4, '23', '2020', 17, 15);
INSERT INTO Produkty VALUES(Produkty_ID_Sek.nextval, 12, 12, 12, '1111111662', 'Tapczix', 'Tapczan z pojemnikiem na pościel, dostępny w 4 wersjach kolorystycznych', 4574, 4, '23', '2020', 58, 10);
INSERT INTO Produkty VALUES(Produkty_ID_Sek.nextval, 13, 13, 13, '1111127924', 'Szufladzix', 'Komoda 5 szuflad, dostępna w 5 kolorach', 6475, 4, '23', '2021', 24, 0);
INSERT INTO Produkty VALUES(Produkty_ID_Sek.nextval, 14, 14, 14, '1111112630', 'Biurkor', 'Biurko proste z szafką, szufladą oraz półką na klawiaturę. Dostępne w 2 kolorach', 5460, 5, '23', '2020', 63, 8);
INSERT INTO Produkty VALUES(Produkty_ID_Sek.nextval, 15, 15, 15, '1111111500', 'Lustix', 'Lustro ozdobne z oświetleniem LED', 9907, 1, '23', '2020', 89, 25);

INSERT INTO Zamowienia VALUES(Zamowienia_ID_Sek.nextval, 1, sysdate - 236, '1', sysdate - 95, '1', sysdate - 36, '1', 1);
INSERT INTO Zamowienia VALUES(Zamowienia_ID_Sek.nextval, 2, sysdate - 208, '0', sysdate - 80, '1', sysdate - 29, '0', 2);
INSERT INTO Zamowienia VALUES(Zamowienia_ID_Sek.nextval, 3, sysdate - 151, '0', sysdate - 72, '0', sysdate - 34, '0', 3);
INSERT INTO Zamowienia VALUES(Zamowienia_ID_Sek.nextval, 4, sysdate - 164, '0', sysdate - 78, '1', sysdate - 37, '1', 4);
INSERT INTO Zamowienia VALUES(Zamowienia_ID_Sek.nextval, 5, sysdate - 209, '1', sysdate - 87, '0', sysdate - 28, '0', 5);
INSERT INTO Zamowienia VALUES(Zamowienia_ID_Sek.nextval, 6, sysdate - 175, '0', sysdate - 86, '0', sysdate - 35, '0', 6);
INSERT INTO Zamowienia VALUES(Zamowienia_ID_Sek.nextval, 7, sysdate - 119, '1', sysdate - 56, '0', sysdate - 32, '0', 7);
INSERT INTO Zamowienia VALUES(Zamowienia_ID_Sek.nextval, 8, sysdate - 297, '0', sysdate - 50, '1', sysdate - 36, '1', 8);
INSERT INTO Zamowienia VALUES(Zamowienia_ID_Sek.nextval, 9, sysdate - 194, '1', sysdate - 90, '1', sysdate - 26, '0', 9);
INSERT INTO Zamowienia VALUES(Zamowienia_ID_Sek.nextval, 10, sysdate - 140, '0', sysdate - 86, '0', sysdate - 43, '1', 10);
INSERT INTO Zamowienia VALUES(Zamowienia_ID_Sek.nextval, 11, sysdate - 109, '0', sysdate - 55, '0', sysdate - 37, '1', 11);
INSERT INTO Zamowienia VALUES(Zamowienia_ID_Sek.nextval, 12, sysdate - 297, '0', sysdate - 97, '0', sysdate - 41, '1', 12);
INSERT INTO Zamowienia VALUES(Zamowienia_ID_Sek.nextval, 13, sysdate - 261, '0', sysdate - 90, '1', sysdate - 45, '1', 13);
INSERT INTO Zamowienia VALUES(Zamowienia_ID_Sek.nextval, 14, sysdate - 282, '1', sysdate - 90, '0', sysdate - 33, '1', 14);
INSERT INTO Zamowienia VALUES(Zamowienia_ID_Sek.nextval, 15, sysdate - 249, '1', sysdate - 75, '1', sysdate - 35, '0', 15);

INSERT INTO Zamowienia_produkty VALUES(Zamowienia_produkty_ID_Sek.nextval, 1, 1, 1);
INSERT INTO Zamowienia_produkty VALUES(Zamowienia_produkty_ID_Sek.nextval, 2, 2, 9);
INSERT INTO Zamowienia_produkty VALUES(Zamowienia_produkty_ID_Sek.nextval, 3, 3, 7);
INSERT INTO Zamowienia_produkty VALUES(Zamowienia_produkty_ID_Sek.nextval, 4, 4, 10);
INSERT INTO Zamowienia_produkty VALUES(Zamowienia_produkty_ID_Sek.nextval, 5, 5, 10);
INSERT INTO Zamowienia_produkty VALUES(Zamowienia_produkty_ID_Sek.nextval, 6, 6, 4);
INSERT INTO Zamowienia_produkty VALUES(Zamowienia_produkty_ID_Sek.nextval, 7, 7, 6);
INSERT INTO Zamowienia_produkty VALUES(Zamowienia_produkty_ID_Sek.nextval, 8, 8, 4);
INSERT INTO Zamowienia_produkty VALUES(Zamowienia_produkty_ID_Sek.nextval, 9, 9, 1);
INSERT INTO Zamowienia_produkty VALUES(Zamowienia_produkty_ID_Sek.nextval, 10, 10, 1);
INSERT INTO Zamowienia_produkty VALUES(Zamowienia_produkty_ID_Sek.nextval, 11, 11, 8);
INSERT INTO Zamowienia_produkty VALUES(Zamowienia_produkty_ID_Sek.nextval, 12, 12, 6);
INSERT INTO Zamowienia_produkty VALUES(Zamowienia_produkty_ID_Sek.nextval, 13, 13, 9);
INSERT INTO Zamowienia_produkty VALUES(Zamowienia_produkty_ID_Sek.nextval, 14, 14, 4);
INSERT INTO Zamowienia_produkty VALUES(Zamowienia_produkty_ID_Sek.nextval, 15, 15, 9);

INSERT INTO Uslugi VALUES(Uslugi_ID_Sek.nextval, 'przeprowadzki', 'Pomoc w zmianie miejsca zamieszkania, noszenie mebli oraz innych artukułów', 5975, 23);
INSERT INTO Uslugi VALUES(Uslugi_ID_Sek.nextval, 'pełny montaż', 'Sprawdzenie stanu, rozpakowanie, montaż mebli', 7828, 23);
INSERT INTO Uslugi VALUES(Uslugi_ID_Sek.nextval, 'dojazd - strefa 1', 'Dojazd do klienta na terenie miasta Kielce', 14959, 23);
INSERT INTO Uslugi VALUES(Uslugi_ID_Sek.nextval, 'dojazd - strefa 2', 'Dojazd do klienta poza miastem Kielce', 7773, 23);
INSERT INTO Uslugi VALUES(Uslugi_ID_Sek.nextval, 'wniesienie', 'Wniesienie paczek lub zmontowanych mebli', 2233, 23);
INSERT INTO Uslugi VALUES(Uslugi_ID_Sek.nextval, 'zniesienie', 'Wyniesienie starych mebli', 4409, 23);
INSERT INTO Uslugi VALUES(Uslugi_ID_Sek.nextval, 'ustawienie mebli', 'Ustawienie zgodnie z projektem lub życzeniem klienta', 13913, 23);
INSERT INTO Uslugi VALUES(Uslugi_ID_Sek.nextval, 'sprzątanie', 'Wywóz elementów zabezpieczających i opakowań', 13909, 23);
INSERT INTO Uslugi VALUES(Uslugi_ID_Sek.nextval, 'montaż luster/obrazow', 'Przygotowanie ściany do wiercenia, powieszenie luster lub innych elementów dekoracyjnych oraz ich wypoziomowanie', 2032, 23);
INSERT INTO Uslugi VALUES(Uslugi_ID_Sek.nextval, 'docinanie', 'Docinanie mebli pod wymiar', 2630, 23);
INSERT INTO Uslugi VALUES(Uslugi_ID_Sek.nextval, 'serwis', 'Serwisowanie mebli, naprawa spuchniętych płyt wiórowych, naprawa rys i wgłębień, oklejanie fornirem, poziomowanie drzwiczek', 7891, 23);
INSERT INTO Uslugi VALUES(Uslugi_ID_Sek.nextval, 'planowanie kuchni', 'Szkic kuchni wraz z wyceną w tym montaż i transport, pełen projekt 3D, wymiarowanie pomieszczenia', 3618, 23);
INSERT INTO Uslugi VALUES(Uslugi_ID_Sek.nextval, 'projektowanie wnętrz', 'Projekt 3D pomieszczeń mieszkalnych, koloże produktowe, dopasowanie kolorystyki ścian i podłóg', 1348, 23);
INSERT INTO Uslugi VALUES(Uslugi_ID_Sek.nextval, 'projektowanie dla firm', 'Aranżacja wnętrza firmowego, w tym wymiarowanie, produkcja lub przeprowadzenie zamówienia mebli na wymiar, doradztwo materiałowe', 9434, 23);
INSERT INTO Uslugi VALUES(Uslugi_ID_Sek.nextval, 'montaż sprzętu AGD i RTV', 'Montaż sprzętu elektronicznego oraz artukułów gospodarstwa domowego', 11761, 23);

INSERT INTO Zlecenia_uslug VALUES(Zlecenia_uslug_ID_Sek.nextval, 1, 1, sysdate - 295,  '1', sysdate - 60, '1', sysdate + 45);
INSERT INTO Zlecenia_uslug VALUES(Zlecenia_uslug_ID_Sek.nextval, 2, 2, sysdate - 291,  '1', sysdate - 66, '1', sysdate + 48);
INSERT INTO Zlecenia_uslug VALUES(Zlecenia_uslug_ID_Sek.nextval, 3, 3, sysdate - 127,  '0', sysdate - 69, '1', sysdate + 48);
INSERT INTO Zlecenia_uslug VALUES(Zlecenia_uslug_ID_Sek.nextval, 4, 4, sysdate - 237,  '0', sysdate - 96, '0', sysdate + 36);
INSERT INTO Zlecenia_uslug VALUES(Zlecenia_uslug_ID_Sek.nextval, 5, 5, sysdate - 108,  '1', sysdate - 76, '0', sysdate + 39);
INSERT INTO Zlecenia_uslug VALUES(Zlecenia_uslug_ID_Sek.nextval, 6, 6, sysdate - 234,  '1', sysdate - 90, '1', sysdate + 30);
INSERT INTO Zlecenia_uslug VALUES(Zlecenia_uslug_ID_Sek.nextval, 7, 7, sysdate - 205,  '0', sysdate - 74, '1', sysdate + 46);
INSERT INTO Zlecenia_uslug VALUES(Zlecenia_uslug_ID_Sek.nextval, 8, 8, sysdate - 160,  '1', sysdate - 52, '1', sysdate + 41);
INSERT INTO Zlecenia_uslug VALUES(Zlecenia_uslug_ID_Sek.nextval, 9, 9, sysdate - 202,  '0', sysdate - 85, '1', sysdate + 42);
INSERT INTO Zlecenia_uslug VALUES(Zlecenia_uslug_ID_Sek.nextval, 10, 10, sysdate - 132,  '0', sysdate - 51, '0', sysdate + 39);
INSERT INTO Zlecenia_uslug VALUES(Zlecenia_uslug_ID_Sek.nextval, 11, 11, sysdate - 207,  '0', sysdate - 57, '1', sysdate + 33);
INSERT INTO Zlecenia_uslug VALUES(Zlecenia_uslug_ID_Sek.nextval, 12, 12, sysdate - 251,  '0', sysdate - 89, '0', sysdate + 37);
INSERT INTO Zlecenia_uslug VALUES(Zlecenia_uslug_ID_Sek.nextval, 13, 13, sysdate - 116,  '1', sysdate - 75, '1', sysdate + 39);
INSERT INTO Zlecenia_uslug VALUES(Zlecenia_uslug_ID_Sek.nextval, 14, 14, sysdate - 232,  '0', sysdate - 68, '1', sysdate + 33);
INSERT INTO Zlecenia_uslug VALUES(Zlecenia_uslug_ID_Sek.nextval, 15, 15, sysdate - 254,  '0', sysdate - 96, '0', sysdate + 34);

INSERT INTO Pracownicy_zlecen VALUES(Pracownicy_zlecen_ID_Sek.nextval, 4, 1);
INSERT INTO Pracownicy_zlecen VALUES(Pracownicy_zlecen_ID_Sek.nextval, 4, 2);
INSERT INTO Pracownicy_zlecen VALUES(Pracownicy_zlecen_ID_Sek.nextval, 5, 3);
INSERT INTO Pracownicy_zlecen VALUES(Pracownicy_zlecen_ID_Sek.nextval, 5, 4);
INSERT INTO Pracownicy_zlecen VALUES(Pracownicy_zlecen_ID_Sek.nextval, 2, 5);
INSERT INTO Pracownicy_zlecen VALUES(Pracownicy_zlecen_ID_Sek.nextval, 2, 6);
INSERT INTO Pracownicy_zlecen VALUES(Pracownicy_zlecen_ID_Sek.nextval, 7, 7);
INSERT INTO Pracownicy_zlecen VALUES(Pracownicy_zlecen_ID_Sek.nextval, 15, 8);
INSERT INTO Pracownicy_zlecen VALUES(Pracownicy_zlecen_ID_Sek.nextval, 4, 9);
INSERT INTO Pracownicy_zlecen VALUES(Pracownicy_zlecen_ID_Sek.nextval, 12, 10);
INSERT INTO Pracownicy_zlecen VALUES(Pracownicy_zlecen_ID_Sek.nextval, 8, 11);
INSERT INTO Pracownicy_zlecen VALUES(Pracownicy_zlecen_ID_Sek.nextval, 9, 12);
INSERT INTO Pracownicy_zlecen VALUES(Pracownicy_zlecen_ID_Sek.nextval, 6, 13);
INSERT INTO Pracownicy_zlecen VALUES(Pracownicy_zlecen_ID_Sek.nextval, 6, 14);
INSERT INTO Pracownicy_zlecen VALUES(Pracownicy_zlecen_ID_Sek.nextval, 4, 15);
